"""empty message

Revision ID: 4474b1bad584
Revises: 05529cafce2e
Create Date: 2018-04-15 19:37:22.052067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4474b1bad584'
down_revision = '05529cafce2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'deleted')
    # ### end Alembic commands ###
